api/urls.py
from django.urls import path
from rest_framework_simplejwt import views as jwt_views

from .views import RegisterView, LoginView, PropertyView, HotelView, UserView, BookmarkHotelView, BookmarkPropertyView, FeaturedPropertyView, UpdateUserView, UnBookmarkPropertyView

urlpatterns = [
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('me/', UserView.as_view(), name='user'),
    path('properties/', PropertyView.as_view(), name='properties'),
    path('hotels/', HotelView.as_view(), name='hotels'),
    path('bookmark/hotel/', BookmarkHotelView.as_view(), name='bookmark-hotel'),
    path('bookmark/property/', BookmarkPropertyView.as_view(), name='bookmark-property'),
    path('unbookmark/property/', UnBookmarkPropertyView.as_view(), name='bookmark-property'),
    path('featured/property/', FeaturedPropertyView.as_view(), name='featured-property'),
    path('update/me/', UpdateUserView.as_view(), name='update-user'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Darader Admin Portal"
admin.site.site_title = "Darader Admin Portal"
admin.site.index_title = "Welcome to Darader Admin Portal"

handler404 = "properties.views.handler404"

urlpatterns = [
    path('secret-saucer/', admin.site.urls),
    path('', include(('properties.urls', 'properties'), namespace='properties')),
    path('my/', include(('users.urls', 'users'), namespace='users')),
    path('hotel/', include(('hotels.urls', 'hotels'), namespace='hotels')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

properties/urls.py
from django.urls import path

from .views import (
    HomePageView, SearchResultView,
    login_view, password_recovery,
    logout_view, signup_view,
    bookmark_item_view, property_details,
    contact_view, faq_view, activate_view
    )

urlpatterns = [
    path('ajax/signup/', signup_view, name="signup"),
    path('ajax/login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('', HomePageView.as_view(), name="home"),    
    path(
        'search/', SearchResultView.as_view(), 
        {"queryset": "search"}, name="search"),
    path(
        'rent/', SearchResultView.as_view(),
        {"queryset": "rent"}, name="rent"),
    path(
        'sale/', SearchResultView.as_view(),
        {"queryset": "sale"}, name="sale"),
    path(
        'lease/', SearchResultView.as_view(),
        {"queryset": "lease"}, name="lease"),
    path(
        'all/', SearchResultView.as_view(),
        {"queryset": "all"}, name="all"),
    path(
        'flats/', SearchResultView.as_view(),
        {"queryset": "flat"}, name="flats"),
    path(
        'lands/', SearchResultView.as_view(),
        {"queryset": "land"}, name="lands"),
    path(
        'houses/', SearchResultView.as_view(),
        {"queryset": "house"}, name="houses"),
    path(
        'commercial-spaces/', SearchResultView.as_view(),
        {"queryset": "commercial"}, name="commercial_spaces"),
    path(
        'event-centres/', SearchResultView.as_view(),
        {"queryset": "event centre"}, name="event_centres"),
    path(
        'property/<int:pk>/<slug>/',
        property_details, name="property-details"),
    path(
        'ajax/bookmark/', bookmark_item_view, name="bookmark-property"),
    path('forgot-password/', password_recovery, name="forgot-password"),
    path('contact/', contact_view, name="contact"),
    path('faq/', faq_view, name="faq"),
    path('activate/<uidb64>/<token>/', activate_view, name='activate'),
]

properties/forms.py
from django import forms

from properties.models import BookingRequest


class BookingRequestForm(forms.ModelForm):

    class Meta:
        model = BookingRequest
        fields = ['comment', 'mobile_phone']
        widgets = {
            'comment': forms.Textarea(attrs={
                'class': 'contact-form__textarea mb-25', 'cols': 10,
                'placeholder': 'Enter your message',
                'required': True}),
            'mobile_phone': forms.TextInput(attrs={
                'class': 'form-control filter-input', 
                'placeholder': 'Enter your phone number',
                'required': True})
        }


class ContactForm(forms.Form):
    name = forms.CharField(
        required=True, 
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'fname',
            'placeholder': 'Name'
        }))
    email = forms.EmailField(
        required=True, 
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'id': 'email_address',
            'placeholder': 'Email address'
        }))
    message = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'id': 'comment',
            'placeholder': 'Your Message'
        }))

properties/views.py
from django.db.models import Q
from django.urls import reverse
from django.contrib import messages
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import (
    render_to_response,
    redirect, render,
    get_object_or_404)
from django.contrib.auth import login, logout, authenticate
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from users.models import User
from users.forms import UserCreationForm

from .forms import ContactForm, BookingRequestForm as BRForm
from .models import (
    Property, PropertyDetails,
    BookmarkedProperty as Bookmarked)

from .helpers import (
    get_currently_featured,
    email_activate_acct,
    email_booking_request,
    email_contact_us)


from .utils import account_activation_token


def signup_view(request):
    if request.is_ajax and request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=True)
            email_activate_acct(request, user)
            return JsonResponse({"result": "Success"})
        else:
            return JsonResponse({"result": form.errors})
    raise Http404("Page Doesn't Exist!")


def login_view(request):
    if request.is_ajax and request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(
            username=username,
            password=password
            )
        if user is not None and user.is_active:
            login(request, user)
            return JsonResponse({"result": "Success!"})
        else:
            return JsonResponse({"result": "Failed!"})

    raise Http404("Page Doesn't Exist!")


def activate_view(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect(reverse("properties:home"))
    else:
        raise Http404("User Doesn't Exist!")


def logout_view(request):
    logout(request)
    return redirect(reverse("properties:home"))


class HomePageView(TemplateView):

    template_name = "properties/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["for_sale"] = Property.forsale.order_by("created")[:3]
        context["for_rent"] = Property.forrent.order_by("created")[:3]
        context["for_lease"] = Property.forlease.order_by("created")[:3]
        context["recent_properties"] = Property.objects.order_by("created")[:7]
        context["featured"] = get_currently_featured()

        return context

    def post(self, request, *args, **kwargs):
        search_title = self.request.POST.get("location", "")
        property_type = self.request.POST.get("property-type", "")
        property_category = self.request.POST.get("property-category", "")
        bedrooms = self.request.POST.get("bedrooms", 1)
        bathrooms = self.request.POST.get("bathrooms", 1)
        budget = self.request.POST.get("budget", "200000 - 300000").split("-")

        query = PropertyDetails.objects.filter(
            Q(property_obj__title__icontains=search_title) |
            Q(property_obj__property_type=property_type) |
            Q(property_obj__property_category=property_category) |
            Q(bedrooms=int(bedrooms)) | Q(bathrooms=int(bathrooms)) |
            Q(property_obj__price__range=(int(budget[0]), int(budget[1])))
            )

        self.request.session["query"] = list(set([qs.pk for qs in query]))
        return HttpResponseRedirect(reverse("properties:search"))


class SearchResultView(ListView):

    template_name = "properties/serp.html"
    context_object_name = "properties"
    paginate_by = 5

    def get_queryset(self):

        search_title = self.request.GET.get("location", "")
        property_type = self.request.GET.get("property-type", "")
        property_category = self.request.GET.get("property-category", "")
        bedrooms = self.request.GET.get("bedrooms", 1)
        bathrooms = self.request.GET.get("bathrooms", 1)
        budget = self.request.GET.get("budget", "200000 - 300000").split("-")
        basketball = self.request.GET.get("basketball")
        swimming_pool = self.request.GET.get("swimming-pool")
        gym = self.request.GET.get("gym")
        wheelchair = self.request.GET.get("wheelchair")

        submit_action = self.request.GET.get("submit")

        new_query = PropertyDetails.objects.filter(
            Q(property_obj__title__icontains=search_title) |
            Q(property_obj__property_type=property_type) |
            Q(property_obj__property_category=property_category) |
            Q(bedrooms=int(bedrooms)) | Q(bathrooms=int(bathrooms)) |
            Q(property_obj__price__range=(int(budget[0]), int(budget[1]))) |
            Q(has_basketball_court=bool(basketball)) |
            Q(has_swimming_pool=bool(swimming_pool)) | Q(has_gym=bool(gym)) |
            Q(is_wheelchair_friendly=bool(wheelchair))
            )

        category_param = ["rent", "sale", "lease", ]

        type_param = [
            "flat", "land",
            "house", "commercial",
            "event centre", ]

        if self.kwargs["queryset"] == "search":
            if submit_action:
                return new_query
            else:
                try:
                    return [PropertyDetails.objects.get(pk=qs) for qs in self.request.session["query"]]
                except KeyError:
                    return ""

        if self.kwargs["queryset"] in category_param:
            if submit_action:
                return new_query
            else:
                return PropertyDetails.objects.filter(
                    property_obj__property_category=self.kwargs["queryset"])

        if self.kwargs["queryset"] in type_param:
            if submit_action:
                return new_query
            else:
                return PropertyDetails.objects.filter(
                    property_obj__property_type=self.kwargs["queryset"])

        if self.kwargs["queryset"] == "all":
            if submit_action:
                return new_query
            else:
                return PropertyDetails.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["qs"] = self.request.META["QUERY_STRING"]
        context["recent_properties"] = Property.objects.order_by("created")[:5]
        context["total_flats"] = Property.objects.filter(
                                    property_type="flat").count()
        context["total_houses"] = Property.objects.filter(
                                    property_type="house").count()
        context["total_lands"] = Property.objects.filter(
                                    property_type="land").count()
        context["total_commercials"] = Property.objects.filter(
                                    property_type="commercial").count()
        context["total_event_centres"] = Property.objects.filter(
                                    property_type="event centre").count()
        return context


def property_details(request, pk, slug):
    context = {}

    obj = PropertyDetails.objects.get(
        property_obj__id=pk,
        property_obj__slug=slug)

    if request.method == "POST":
        bookingform = BRForm(request.POST)

        if bookingform.is_valid():
            booking_obj = bookingform.save(commit=False)
            booking_obj.company = obj.property_obj.owner
            booking_obj.property_details = obj
            booking_obj.client = request.user
            booking_obj.status = "booked"
            booking_obj.save()
            email_booking_request(request, obj.property_obj.owner.manager)
            messages.success(request, "Successfully Booked!")
        else:
            messages.error(request, bookingform.errors)

    else:
        bookingform = BRForm()

    context["object"] = obj
    context["recent_properties"] = Property.objects.order_by("created")[:3]
    context["featured"] = get_currently_featured()
    context["images"] = [x.image.url for x in obj.property_obj.gallery.all()]
    context["similar"] = PropertyDetails.objects.filter(
        Q(property_obj__title__icontains=obj.property_obj.title) |
        Q(property_obj__property_type=obj.property_obj.property_type) |
        Q(property_obj__lga=obj.property_obj.lga) |
        Q(property_obj__owner=obj.property_obj.owner)
    )
    context["bookingform"] = bookingform

    return render(request, 'properties/single-property.html', context)


def bookmark_item_view(request):
    if request.is_ajax and request.method == "POST":
        property_id = request.POST.get('propertyID')

        if request.user.is_authenticated:
            property_obj = get_object_or_404(Property, id=property_id)

            try:
                Bookmarked.objects.get(
                    owner=request.user,
                    property_obj=property_obj)
                return JsonResponse({"result": "Already Bookmarked!"})
            except Bookmarked.DoesNotExist:
                Bookmarked.objects.create(
                    owner=request.user, property_obj=property_obj)
                return JsonResponse({"result": "Success!"})

        return JsonResponse({"result": "Unauthorized"})
    else:
        raise Http404("Page Doesn't Exist!")


def contact_view(request):
    context = {}
    if request.method == "POST":
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            data = {
                "name": contact_form.cleaned_data["name"],

properties/templates/base.html
{% load static %}

<!DOCTYPE html>
<html dir="ltr" lang="en-US">

<head>
    <!-- Metas -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Lucky Adogun" />
    <!-- Links -->
    <link rel="icon" type="image/png" href="#" />
    <!-- google fonts-->
    <!-- <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"> -->
    <!-- Plugins CSS -->
    <link href="{% static 'assets/css/plugin.css' %}" rel="stylesheet" />
    <!-- style CSS -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />

    <!-- Document Title -->
    <title>{% block title %} {% endblock title %}</title>
</head>

<body>
    <!--Preloader starts-->
    <div class="preloader js-preloader">
        <img src="{% static 'assets/images/preloader.gif' %}" alt="...">
    </div>
    <!--Preloader ends-->

    <!--Page Wrapper starts-->
    <div class="page-wrapper">

        <!-- Header starts -->
        {% block header %}

        {% endblock %}
        <!-- Header Ends -->


        <!-- content starts -->
        {% block content %}

        {% endblock %}
        <!-- content ends -->


        <!-- Scroll to top starts-->
        <span class="scrolltotop"><i class="lnr lnr-arrow-up"></i></span>
        <!-- Scroll to top ends-->


        <!--Agent Chat box starts-->
        {% block chatbox %}

        {% endblock %}
        <!--Agent Chat box ends-->
    </div>
    <!-- Footer Begins -->
    {% block footer %}

    {% endblock %}
    <!-- Footer Ends -->

    <!--login Modal starts-->
        {% if not user.is_authenticated %} {% include "components/modal.html" %} {% else %} <div></div> {% endif %}
    <!--login Modal ends-->

    <!--Scripts starts-->
    <!--plugin js-->
    <script src="{% static 'assets/js/plugin.js' %}"></script>
    <!--google maps-->
    <!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD_8C7p0Ws2gUu7wo0b6pK9Qu7LuzX2iWY&amp;libraries=places&amp;callback=initAutocomplete"></script> -->
    <!--Main js-->
    <script src="{% static 'assets/js/main.js' %}"></script>
    <!--Scripts ends-->
</body>

</html>

properties/templates/property_base.html
{% load static %}

<!DOCTYPE html>
<html dir="ltr" lang="en-US">

<head>
    <!-- Metas -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Lucky Adogun" />
    <!-- Links -->
    <link rel="icon" type="image/png" href="#" />
    <!-- google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">
    <!-- Plugins CSS -->
    <link href="{% static 'assets/css/plugin.css' %}" rel="stylesheet" />
    <!-- style CSS -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />

    <!-- Document Title -->
    <title>{% block title %} {% endblock title %}</title>
</head>

<body>
    <!--Preloader starts-->
    <div class="preloader js-preloader">
        <img src="{% static 'assets/images/preloader.gif' %}" alt="...">
    </div>
    <!--Preloader ends-->

    <!--Page Wrapper starts-->
    <div class="page-wrapper">

        <!-- Header starts -->
        {% block header %}

        {% endblock %}
        <!-- Header Ends -->


        <!-- content starts -->
        {% block content %}

        {% endblock %}
        <!-- content ends -->


        <!-- Scroll to top starts-->
        <span class="scrolltotop"><i class="lnr lnr-arrow-up"></i></span>
        <!-- Scroll to top ends-->


        <!--Agent Chat box starts-->
        {% block chatbox %}

        {% endblock %}
        <!--Agent Chat box ends-->
    </div>
    <!-- Footer Begins -->
    {% block footer %}

    {% endblock %}
    <!-- Footer Ends -->

    <!--login Modal starts-->
        {% if not user.is_authenticated %} {% include "properties_components/modal.html" %} {% else %} <div></div> {% endif %}
    <!--login Modal ends-->

    <!--Scripts starts-->
    <!--plugin js-->
    <script src="{% static 'assets/js/plugin.js' %}"></script>
    <!--google maps-->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD_8C7p0Ws2gUu7wo0b6pK9Qu7LuzX2iWY&amp;libraries=places&amp;callback=initAutocomplete"></script>
    <!--Main js-->
    <script src="{% static 'assets/js/main.js' %}"></script>
    <!-- custom scripts  -->   
    <script>
        var csrfToken = '{{ csrf_token }}';
        var loginURL = "{% url 'properties:login' %}"
        var signupURL = "{% url 'properties:signup' %}"
        var bookmarkURL = "{% url 'properties:bookmark-property' %}"
    </script> 
    <script src="{% static 'assets/js/ajax-bookmark.js' %}"></script> 
    <script src="{% static 'assets/js/ajax-login.js' %}"></script>
    <script src="{% static 'assets/js/ajax-signup.js' %}"></script> 
    <!--Scripts ends-->
</body>

</html>