api/urls.py
from django.urls import path
from rest_framework_simplejwt import views as jwt_views

from .views import RegisterView, LoginView, PropertyView, HotelView, UserView, BookmarkHotelView, BookmarkPropertyView, FeaturedPropertyView, UpdateUserView, UnBookmarkPropertyView

urlpatterns = [
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('me/', UserView.as_view(), name='user'),
    path('properties/', PropertyView.as_view(), name='properties'),
    path('hotels/', HotelView.as_view(), name='hotels'),
    path('bookmark/hotel/', BookmarkHotelView.as_view(), name='bookmark-hotel'),
    path('bookmark/property/', BookmarkPropertyView.as_view(), name='bookmark-property'),
    path('unbookmark/property/', UnBookmarkPropertyView.as_view(), name='bookmark-property'),
    path('featured/property/', FeaturedPropertyView.as_view(), name='featured-property'),
    path('update/me/', UpdateUserView.as_view(), name='update-user'),
]

hotels/urls.py
from django.urls import path

from .views import (add_hotel_view, hotel_details, hotel_booking_view, 
                    MyHotelView, update_hotel, hotel_delete_view, AllHotelView
                    )

urlpatterns = [
    path('add-hotel/', add_hotel_view, name="add-hotel"),
    path('<str:name>', hotel_details, name="hotel-details"),
    path('room-booking/', hotel_booking_view, name="hotel-room-booking"),
    path('<str:name>/update/', update_hotel, name="update-hotel"),
    path('ajax/hotel/delete/', hotel_delete_view, name="delete-hotel"),
    path('my-hotels/', MyHotelView.as_view(), name="my-hotels"),
    path('all-hotels/', AllHotelView.as_view(), name="all-hotels")
    # path('hotel-bookings/', MyHotelBookingsView.as_view(), name="my-hotel-bookings"),
    # path('ajax/bookings/setup/', booking_setup_view, name="setup-bookings"),
    # path('ajax/bookings/delete/', booking_delete_view, name="delete-bookings"),
    # path('bookmarks/', BookmarkedView.as_view(), name="bookmarked"),
    # path('ajax/bookmarks/delete/', bookmark_delete_view, name="bookmark-delete"), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Darader Admin Portal"
admin.site.site_title = "Darader Admin Portal"
admin.site.index_title = "Welcome to Darader Admin Portal"

handler404 = "properties.views.handler404"

urlpatterns = [
    path('secret-saucer/', admin.site.urls),
    path('', include(('properties.urls', 'properties'), namespace='properties')),
    path('my/', include(('users.urls', 'users'), namespace='users')),
    path('hotel/', include(('hotels.urls', 'hotels'), namespace='hotels')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

properties/urls.py
from django.urls import path

from .views import (
    HomePageView, SearchResultView,
    login_view, password_recovery,
    logout_view, signup_view,
    bookmark_item_view, property_details,
    contact_view, faq_view, activate_view
    )

urlpatterns = [
    path('ajax/signup/', signup_view, name="signup"),
    path('ajax/login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('', HomePageView.as_view(), name="home"),    
    path(
        'search/', SearchResultView.as_view(), 
        {"queryset": "search"}, name="search"),
    path(
        'rent/', SearchResultView.as_view(),
        {"queryset": "rent"}, name="rent"),
    path(
        'sale/', SearchResultView.as_view(),
        {"queryset": "sale"}, name="sale"),
    path(
        'lease/', SearchResultView.as_view(),
        {"queryset": "lease"}, name="lease"),
    path(
        'all/', SearchResultView.as_view(),
        {"queryset": "all"}, name="all"),
    path(
        'flats/', SearchResultView.as_view(),
        {"queryset": "flat"}, name="flats"),
    path(
        'lands/', SearchResultView.as_view(),
        {"queryset": "land"}, name="lands"),
    path(
        'houses/', SearchResultView.as_view(),
        {"queryset": "house"}, name="houses"),
    path(
        'commercial-spaces/', SearchResultView.as_view(),
        {"queryset": "commercial"}, name="commercial_spaces"),
    path(
        'event-centres/', SearchResultView.as_view(),
        {"queryset": "event centre"}, name="event_centres"),
    path(
        'property/<int:pk>/<slug>/',
        property_details, name="property-details"),
    path(
        'ajax/bookmark/', bookmark_item_view, name="bookmark-property"),
    path('forgot-password/', password_recovery, name="forgot-password"),
    path('contact/', contact_view, name="contact"),
    path('faq/', faq_view, name="faq"),
    path('activate/<uidb64>/<token>/', activate_view, name='activate'),
]

hotels/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, Http404

from users.decorators import staff_or_manager_required
from .helpers import hotel_email_booking_request, user_hotel_email_booking_request
from .forms import HotelForm, RoomForm, HotelPhotosForm, FAQForm, HotelBookingRequestForm, HotelUpdateForm, HotelPhotosUpdateForm
from .models import Hotel, HotelPhotos, Room, FAQ, HotelBookingRequest, BookmarkedHotel


@login_required
@staff_or_manager_required
def add_hotel_view(request):
    context = {}
    if request.is_ajax and request.method == "POST":
        hotel_form = HotelForm(request.POST)
        hotel_photos_form = HotelPhotosForm(request.POST, request.FILES)
        room_form = RoomForm(request.POST)
        faq_form = FAQForm(request.POST)
        forms = all(
            [hotel_form.is_valid(), hotel_photos_form.is_valid(),
                room_form.is_valid(), faq_form.is_valid()])
        if forms:
            hotel_instance = hotel_form.save(commit=False)
            hotel_instance.creator = request.user
            hotel_instance.save()
            
            uploaded_images = request.FILES.getlist('photo')
            # Since the form accept submission without images
            # Make sure you don't loop when the image list is empty
            if uploaded_images:
                for image in uploaded_images:
                    uploaded_image = HotelPhotos(photo=image, hotel=hotel_instance)
                    uploaded_image.save()
            room_names = request.POST.getlist('room_name')
            prices = request.POST.getlist('price')
            infos = request.POST.getlist('information')
            for name, price, info in zip(room_names, prices, infos):
                room = Room(
                    room_name=name,
                    price=price,
                    information=info,
                    hotel=hotel_instance
                )
                room.save()
            questions = request.POST.getlist('question')
            answers = request.POST.getlist('answer')
            for question, answer in zip(questions, answers):
                faq = FAQ(
                    question=question,
                    answer=answer,
                    hotel=hotel_instance
                )
                faq.save()
            return JsonResponse({"result": "Success"})

        else:
            return JsonResponse({"result": "Failed"})
    else:
        hotel_form = HotelForm
        hotel_photos_form = HotelPhotosForm
        room_form = RoomForm
        faq_form = FAQForm
    context['hotel_form'] = hotel_form
    context['hotel_photos_form'] = hotel_photos_form
    context['room_form'] = room_form
    context['faq_form'] = faq_form

    return render(request, 'hotels/add_hotel.html', context)


def hotel_details(request, name):
    context = {}

    obj = Hotel.objects.get(name=name)

    if request.method == "POST":
        hotel_bookingform = HotelBookingRequestForm(request.POST)

        if hotel_bookingform.is_valid():
            booking_obj = bookingform.save(commit=False)
            booking_obj.company = obj.property_obj.owner
            booking_obj.property_details = obj
            booking_obj.client = request.user
            booking_obj.status = "booked"
            booking_obj.save()
            email_booking_request(request, obj.property_obj.owner.manager)
            messages.success(request, "Successfully Booked!")
        else:
            messages.error(request, hotel_bookingform.errors)

    else:
        hotel_bookingform = HotelBookingRequestForm()

    context["object"] = obj
    context["recent_hotels"] = Hotel.objects.order_by("created").reverse()[:3]
    context["images"] = [x.photo.url for x in obj.hotelPhotos.all()]    
    context["hotel_bookingform"] = hotel_bookingform

    return render(request, 'hotels/single_hotel.html', context)

@method_decorator([staff_or_manager_required], name='dispatch')
class MyHotelView(LoginRequiredMixin, ListView):
    template_name = "hotels/my_hotels.html"
    context_object_name = "hotels"
    paginate_by = 5

    def get_queryset(self):
        if self.request.user.is_staff:
            return Hotel.objects.filter(creator=self.request.user)

@login_required(login_url='properties:login')
def hotel_booking_view(request):
    room_id = request.POST.get('room_id')
    hotel_id = request.POST.get('hotel_id')
    try:
        room = Room.objects.get(pk=room_id)
        hotel = Hotel.objects.get(pk=hotel_id)
        hotel_email = hotel.creator.email
        hotel_name = hotel.name
        room_name = room.room_name
        user_name = request.user.username
        user_email = request.user.email        
        hotel_email_booking_request(hotel_email, hotel_name, user_name, room_name, user_email)        
        user_hotel_email_booking_request(user_email, user_name, room_name, hotel_name)
        return JsonResponse({"result": "Success"})
    except Room.DoesNotExist:
        return JsonResponse({"result": "Failed"})
    except Hotel.DoesNotExist:
        return JsonResponse({"result": "Failed"})

@login_required
@staff_or_manager_required
def hotel_delete_view(request):
    if request.is_ajax and request.method == "POST":
        hotel_id = request.POST.get("hotelID")
        hotel_obj = get_object_or_404(Hotel, pk=hotel_id)

        if hotel_obj.creator == request.user:
            hotel_obj.delete()
            return JsonResponse({"result": "Success!"})
        return JsonResponse({"result": "Unauthorized Access!"})
    raise Http404("Page Doesn't Exist!")

@login_required
@staff_or_manager_required
def update_hotel(request, name=None):
    context = {}

    hotel_obj = get_object_or_404(Hotel, name=name)

    if not hotel_obj.creator == request.user:
        raise Http404("Unauthorized access!")

    if request.is_ajax and request.method == "POST":

        hotel_form = HotelUpdateForm(request.POST, instance=hotel_obj)
        hotel_photos_form = HotelPhotosUpdateForm(request.POST, request.FILES)
        forms = all([
                hotel_form.is_valid(),
                hotel_photos_form.is_valid()])
        if forms:
            hotel_instance = hotel_form.save()
            uploaded_images = request.FILES.getlist('photo')
            if uploaded_images:
                for image in uploaded_images:
                    uploaded_image = HotelPhotos(photo=image, hotel=hotel_instance)
                    uploaded_image.save()
            faq_ids = request.POST.getlist('faq_id')
            questions = request.POST.getlist('question')
            answers = request.POST.getlist('answer')
            room_ids = request.POST.getlist('room_id')
            room_names = request.POST.getlist('room_name')
            prices = request.POST.getlist('price')
            infos = request.POST.getlist('information')
            for room_id, room_name, room_price, room_info in zip(room_ids, room_names, prices, infos):
                # If the room has an id, then update its details
                if room_id:
                    room_instance = Room.objects.get(id=room_id)
                    room_instance.room_name = room_name
                    room_instance.price = room_price
                    room_instance.information = room_info
                    room_instance.save()
                # If it doesn't have an id, create a new room as it doesn't exist
                else:
                    room_instance = Room(room_name=room_name, price=room_price, information=room_info, hotel=hotel_instance)
                    room_instance.save()
            for faq_id, question, answer in zip(faq_ids, questions, answers):
                # If the faq has an id, update the room details
                if faq_id:
                    faq_instance = FAQ.objects.get(id=faq_id)
                    faq_instance.question = question
                    faq_instance.answer = answer
                    faq_instance.save()
                # If the faq doesn't have an id, create a new room
                else:
                    faq_instance = FAQ(question=question, answer=answer, hotel=hotel_instance)
                    faq_instance.save()            
            return JsonResponse({"result": "Success"})
    else:
        hotel_form = HotelUpdateForm(instance=hotel_obj)
        hotel_photos_form = HotelPhotosUpdateForm()
    context["hotel_form"] = hotel_form
    context["hotel_photos_form"] = hotel_photos_form
    context["hotel"] = hotel_obj

    return render(request, 'hotels/update_hotel.html', context)

# ALL HOTELS
class AllHotelView(ListView):
    template_name = "hotels/all_hotels.html"
    context_object_name = "hotels"
    paginate_by = 5

    def get_queryset(self):
        return Hotel.objects.order_by("created").reverse()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["recent_hotels"] = Hotel.objects.order_by("created").reverse()[:3]
        return context

hotels/templates/hotels/my_hotels.html
{% extends "user_base.html" %}
{% load static %}
{% load humanize %}

{% block title %} Find amazing properties in Nigeria {% endblock %}

<div class="page-wrapper">
    {% block sidebar %}
    {% include "user_components/dashboard__sidebar.html" %}
    {% endblock %}

    {% block content %}
    <!--Sidebar Menu ends-->
    <!--Dashboard content Wrapper starts-->
    <div class="dash-content-wrap">
        <!-- Top header starts-->
        {% include "user_components/dashboard__header.html" %}
        <!-- Top header ends-->
        <!-- Dashboard Content starts-->
        <div class="dash-content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="recent-activity my-listing">
                            <div class="act-title">
                                {% if user.is_staff %}
                                <h5>Manage Listings</h5>
                                {% else %}
                                <h5>My Listings</h5>
                                {% endif %}
                            </div>
                            <div class="viewd-item-wrap">
                                {% if hotels %}
                                {% for hotel in hotels %}
                                <div class="most-viewed-item">
                                    <div class="most-viewed-img">
                                        {% for img in hotel.hotelPhotos.all %}
                                        {% if forloop.first %}
                                        <a href="{% url 'hotels:hotel-details' hotel.name %}" target="_blank">
                                            <img src="{{ img.photo.url }}" alt="{{hotel.name}}">
                                        </a>
                                        {% endif %}
                                        {% endfor %}
                                        <ul class="feature_text">
                                            <li class="feature_or"> <span>FOR
                                                    {{ hotel.hotel_type|upper }}</span></li>
                                        </ul>
                                    </div>
                                    <div class="most-viewed-detail">
                                        <h3><a href="{% url 'hotels:hotel-details' hotel.name %}"
                                                target="_blank">{{ hotel.name }}</a></h3>
                                        <p class="list-address"><i class="fas fa-map-marker-alt"></i>{{ hotel.address }}
                                        </p>
                                        <div class="trend-open">
                                            <p>₦{{ hotel.average_price|floatformat|intcomma }}</p>
                                        </div>
                                        <div class="ratings">
                                            <i class="ion-ios-star"></i>
                                            <i class="ion-ios-star"></i>
                                            <i class="ion-ios-star"></i>
                                            <i class="ion-ios-star"></i>
                                            <i class="ion-ios-star-half"></i>
                                        </div>
                                        <!-- <div class="views">Views : <span>178</span></div> -->
                                    </div>
                                    <div class="listing-button">
                                        <a href="{% url 'hotels:update-hotel' hotel.name %}" class="btn v3"><i
                                                class="ion-edit"></i> Edit</a>
                                        <a href="#" class="btn v4"
                                            onclick="deleteHotel('{{ hotel.name }}', '{{ hotel.id }}');"><i
                                                class="ion-android-delete"></i> Delete</a>
                                    </div>
                                </div>
                                {% endfor %}
                                {% else %}
                                <p style="text-align: center;">You currently have no properties</p>
                                {% endif %}
                            </div>
                            <!--pagination starts-->
                            {% if is_paginated %}
                            <div class="post-nav nav-res pt-50  ">
                                <div class="row">
                                    <div class="col-md-8 offset-md-2  col-xs-12 ">
                                        <div class="page-num text-center">
                                            <ul>
                                                {% for i in paginator.page_range %}
                                                {% if page_obj.number == i %}
                                                <li class="active"><a
                                                        href="?{{ qs }}&page={{ page_obj.page_number }}">{{ i }}</a>
                                                </li>
                                                {% else %}
                                                <li><a href="?{{ qs }}&page={{ i }}">{{ i }}</a></li>
                                                {% endif %}
                                                {% endfor %}

                                                {% if page_obj.has_next %}
                                                <li><a href="?{{ qs }}&page={{ page_obj.next_page_number }}"><i
                                                            class="lnr lnr-chevron-right"></i></a></li>
                                                {% endif %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                            <!--pagination ends-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Dashboard Content ends-->
        <!--Dashboard footer starts-->
        {% include "user_components/dashboard__footer.html" %}
        <!--Dashboard footer ends-->
    </div>
    <!--Dashboard content Wrapper ends-->
</div>
{% endblock %}

{% block scripts %}
<script>

    function deleteHotel(hotel, hotelID) {
        var action = confirm(`Confirm deletion of: ${hotel}`);
        if (action == true) {
            $.ajax({
                type: "POST",
                url: "{% url 'hotels:delete-hotel' %}",
                dataType: "JSON",
                data: {
                    hotelID: hotelID,
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                },
                success: function (response) {
                    var result = response["result"];
                    if (result == "Success!") {
                        location.reload();
                    } else {
                        alert(result);
                    };
                },
                error: function (response) {
                    var result = response["result"];
                    alert("Error! Something went wrong!");
                }
            });
        };
    };
</script>
{% endblock %}