api/urls.py
from django.urls import path
from rest_framework_simplejwt import views as jwt_views

from .views import RegisterView, LoginView, PropertyView, HotelView, UserView, BookmarkHotelView, BookmarkPropertyView, FeaturedPropertyView, UpdateUserView, UnBookmarkPropertyView

urlpatterns = [
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('me/', UserView.as_view(), name='user'),
    path('properties/', PropertyView.as_view(), name='properties'),
    path('hotels/', HotelView.as_view(), name='hotels'),
    path('bookmark/hotel/', BookmarkHotelView.as_view(), name='bookmark-hotel'),
    path('bookmark/property/', BookmarkPropertyView.as_view(), name='bookmark-property'),
    path('unbookmark/property/', UnBookmarkPropertyView.as_view(), name='bookmark-property'),
    path('featured/property/', FeaturedPropertyView.as_view(), name='featured-property'),
    path('update/me/', UpdateUserView.as_view(), name='update-user'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Darader Admin Portal"
admin.site.site_title = "Darader Admin Portal"
admin.site.index_title = "Welcome to Darader Admin Portal"

handler404 = "properties.views.handler404"

urlpatterns = [
    path('secret-saucer/', admin.site.urls),
    path('', include(('properties.urls', 'properties'), namespace='properties')),
    path('my/', include(('users.urls', 'users'), namespace='users')),
    path('hotel/', include(('hotels.urls', 'hotels'), namespace='hotels')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

properties/urls.py
from django.urls import path

from .views import (
    HomePageView, SearchResultView,
    login_view, password_recovery,
    logout_view, signup_view,
    bookmark_item_view, property_details,
    contact_view, faq_view, activate_view
    )

urlpatterns = [
    path('ajax/signup/', signup_view, name="signup"),
    path('ajax/login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('', HomePageView.as_view(), name="home"),    
    path(
        'search/', SearchResultView.as_view(), 
        {"queryset": "search"}, name="search"),
    path(
        'rent/', SearchResultView.as_view(),
        {"queryset": "rent"}, name="rent"),
    path(
        'sale/', SearchResultView.as_view(),
        {"queryset": "sale"}, name="sale"),
    path(
        'lease/', SearchResultView.as_view(),
        {"queryset": "lease"}, name="lease"),
    path(
        'all/', SearchResultView.as_view(),
        {"queryset": "all"}, name="all"),
    path(
        'flats/', SearchResultView.as_view(),
        {"queryset": "flat"}, name="flats"),
    path(
        'lands/', SearchResultView.as_view(),
        {"queryset": "land"}, name="lands"),
    path(
        'houses/', SearchResultView.as_view(),
        {"queryset": "house"}, name="houses"),
    path(
        'commercial-spaces/', SearchResultView.as_view(),
        {"queryset": "commercial"}, name="commercial_spaces"),
    path(
        'event-centres/', SearchResultView.as_view(),
        {"queryset": "event centre"}, name="event_centres"),
    path(
        'property/<int:pk>/<slug>/',
        property_details, name="property-details"),
    path(
        'ajax/bookmark/', bookmark_item_view, name="bookmark-property"),
    path('forgot-password/', password_recovery, name="forgot-password"),
    path('contact/', contact_view, name="contact"),
    path('faq/', faq_view, name="faq"),
    path('activate/<uidb64>/<token>/', activate_view, name='activate'),
]

users/urls.py
from django.urls import path

from .views import (
    DashboardView, MyPropertyView,
    MyBookingsView, add_property,
    MyAccountView, account_update_view,
    BookmarkedView, property_delete_view,
    booking_delete_view, booking_setup_view,
    update_property,  bookmark_delete_view,
    add_company_view, update_company_view,
    ajax_load_lga)

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name="dashboard"),
    path(
        'properties/', MyPropertyView.as_view(),
        {"queryset": "listing"}, name="my-properties"),
    path(
        'properties/manage/', MyPropertyView.as_view(),
        {"queryset": "manage"}, name='manage-properties'),
    path('ajax-load-lga/', ajax_load_lga, name="ajax-load-lga"),
    path('add-property/', add_property, name="add-property"),    
    path(
        'ajax/properties/delete/',
        property_delete_view,
        name="delete-property"),
    path('property/<int:pk>/update/', update_property, name="update-property"),
    path('bookings/', MyBookingsView.as_view(), name="my-bookings"),
    path('ajax/bookings/setup/', booking_setup_view, name="setup-bookings"),
    path('ajax/bookings/delete/', booking_delete_view, name="delete-bookings"),
    path('bookmarks/', BookmarkedView.as_view(), name="bookmarked"),
    path('ajax/bookmarks/delete/', bookmark_delete_view, name="bookmark-delete"),
    path('account/', MyAccountView.as_view(), name="account"),
    path('account/update/', account_update_view, name="update-account"),
    path('company/add/', add_company_view, name="add-company"),
    path('company/update/', update_company_view, name="update-company"),    
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext as _

from .manager import CustomUserManager
from .utils import validate_phone


class User(AbstractUser):
    username = models.CharField(_("username"), max_length=100, unique=True)
    email = models.EmailField(_("email"), max_length=250, unique=True)
    is_staff = models.BooleanField(_("staff"), default=False, blank=True, null=True)
    state = models.ForeignKey('properties.State', on_delete=models.CASCADE, null=True)
    is_admin = models.BooleanField(_("admin"), default=False, blank=True, null=True)
    is_account_manager = models.BooleanField(_("account manager"), default=False, blank=True, null=True)
    is_active = models.BooleanField(_("active user"), default=True, blank=True)
    facebook = models.URLField(max_length=255, blank=True, null=True)
    twitter = models.URLField(max_length=255, blank=True, null=True)
    instagram = models.URLField(max_length=255, blank=True, null=True)    
    mobile_phone = models.CharField(
        validators=[validate_phone], max_length=17,
        null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    @property
    def full_name(self):
        return self.get_full_name()

    def __str__(self):
        return self.username

users/views.py
from django.core import serializers
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.template.loader import render_to_string
from django.http import Http404, JsonResponse, HttpResponse
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import (
            get_object_or_404, render,
            redirect, reverse)

from .forms import (
    PropertyForm,
    GalleryForm,
    PropertyDetailsForm,
    PropertyUpdateForm,
    DetailsUpdateForm,
    GalleryUpdateForm,
    FloorPlanForm,
    FloorPlanUpdateForm,
    AccountUpdateForm,
    CompanyForm, CompanyUpdateForm
    )

from .decorators import (
    staff_or_manager_required, 
    manager_required)

from .helpers import email_booking_confirmed

from properties.models import (
    Property, Company,
    BookingRequest, Gallery,
    BookmarkedProperty, LGA,
    PropertyDetails, FloorPlan)

from hotels.models import Hotel


@method_decorator([login_required], name='dispatch')
class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "users/index.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["recent_properties"] = Property.objects.order_by("created")[:3]
        context["recent_hotels"] = Hotel.objects.order_by("created").reverse()[:3]

        return context


@method_decorator([staff_or_manager_required], name='dispatch')
class MyPropertyView(LoginRequiredMixin, ListView):
    template_name = "users/my_properties.html"
    context_object_name = "properties"
    paginate_by = 5

    def get_queryset(self):
        if self.kwargs["queryset"] == "manage":
            if self.request.user.is_staff:
                return Property.objects.filter(state=self.request.user.state)

        if self.kwargs["queryset"] == "listing":
            company = Company.objects.get(manager=self.request.user)
            return Property.objects.filter(owner=company)


@login_required
@staff_or_manager_required
def property_delete_view(request):
    company = get_object_or_404(Company, manager=request.user)

    if request.is_ajax and request.method == "POST":
        property_id = request.POST.get("propertyID")
        property_obj = get_object_or_404(Property, id=property_id)

        if property_obj.owner == company:
            property_obj.delete()
            return JsonResponse({"result": "Success!"})
        return JsonResponse({"result": "Unauthorized Access!"})

    raise Http404("Page Doesn't Exist!")


def ajax_load_lga(request):
    if request.is_ajax and request.method == "GET":
        state_id = request.GET.get('stateID')
        lga = LGA.objects.filter(state__id=state_id).order_by('name')        
        html = render_to_string('users/lga_dropdown.html', {'lgas': lga})
        return HttpResponse(html)


@login_required
@manager_required
def add_property(request):
    context = {}

    if request.is_ajax and request.method == "POST":

        property_form = PropertyForm(request.POST, prefix="form1")
        gallery_form = GalleryForm(request.POST, request.FILES)
        floorplan_form = FloorPlanForm(request.POST, request.FILES)
        property_details_form = PropertyDetailsForm(
            request.POST, prefix="form2")

        print('PD:', property_details_form.errors)

        forms = all([
            property_form.is_valid(),
            gallery_form.is_valid(),
            floorplan_form.is_valid(),
            property_details_form.is_valid()])

        if forms:
            property_obj = property_form.save(commit=False)
            property_obj.owner = Company.objects.get(manager=request.user.id)
            property_obj.lga = LGA.objects.get(id=request.POST["lgaID"])
            property_obj.save()

            uploaded_images = request.FILES.getlist('image') or request.FILES.get('image')
            floor_image = request.FILES.get('floor_image')

            for img in uploaded_images:
                gallery = Gallery(
                    property_obj=property_obj,
                    image=img)
                gallery.save()

            floor_plan = FloorPlan(
                property_obj=property_obj,
                floor_image=floor_image,
                title=floorplan_form.cleaned_data['title'],
                size=floorplan_form.cleaned_data['size'],
                rooms=floorplan_form.cleaned_data['rooms'],
                bathrooms=floorplan_form.cleaned_data['bathrooms'],
                )
            floor_plan.save()

            property_details = property_details_form.save(commit=False)
            property_details.property_obj = property_obj
            property_details.save()

            return JsonResponse({"result": "Success"})

        else:
            return JsonResponse({"result": "Failed"})

    else:
        property_form = PropertyForm(prefix="form1")
        gallery_form = GalleryForm()
        floorplan_form = FloorPlanForm()
        property_details_form = PropertyDetailsForm(prefix="form2")

    context["property_form"] = property_form
    context["gallery_form"] = gallery_form
    context["floorplan_form"] = floorplan_form
    context["property_details_form"] = property_details_form

    return render(request, 'users/add_property.html', context)


@login_required
@staff_or_manager_required
def update_property(request, pk=None):
    context = {}

    property_obj = get_object_or_404(Property, id=pk)
    prop_details = get_object_or_404(
        PropertyDetails, property_obj=property_obj)
    floor_plan = get_object_or_404(FloorPlan, property_obj=property_obj)

    if not property_obj.owner.manager == request.user:
        raise Http404("Unauthorized access!")

    if request.is_ajax and request.method == "POST":

        property_form = PropertyUpdateForm(
            request.POST, instance=property_obj, prefix="form1")
        gallery_form = GalleryUpdateForm(request.POST, request.FILES)
        floorplan_form = FloorPlanUpdateForm(
            request.POST, request.FILES, instance=floor_plan)
        property_details_form = DetailsUpdateForm(
            request.POST, instance=prop_details, prefix="form2")

        forms = all([
                property_form.is_valid(),
                gallery_form.is_valid(),
                floorplan_form.is_valid(),
                property_details_form.is_valid()])

        if forms:
            property_obj = property_form.save()
            property_details_form.save()
            floorplan_form.save()

            uploaded_images = request.FILES.getlist('image')            

            for img in uploaded_images:
                gallery = Gallery(
                    property_obj=property_obj,
                    image=img)
                gallery.save()         

            return JsonResponse({"result": "Success"})
    else:
        property_form = PropertyUpdateForm(
            instance=property_obj, prefix="form1")
        gallery_form = GalleryUpdateForm()
        floorplan_form = FloorPlanUpdateForm(instance=floor_plan)
        property_details_form = DetailsUpdateForm(
            instance=prop_details, prefix="form2")

    context["property_form"] = property_form
    context["gallery_form"] = gallery_form
    context["floorplan_form"] = floorplan_form
    context["property_details_form"] = property_details_form
    context["property"] = property_obj

    return render(request, 'users/update_property.html', context)


@method_decorator([login_required], name='dispatch')
class MyBookingsView(LoginRequiredMixin, ListView):
    template_name = "users/my_bookings.html"
    context_object_name = "bookings"
    paginate_by = 10

    def get_queryset(self):
        return BookingRequest.objects.filter(
            company__manager=self.request.user,
            status="booked")


@login_required
@manager_required
def booking_delete_view(request):
    company = get_object_or_404(Company, manager=request.user)

    if request.is_ajax and request.method == "POST":
        booking_id = request.POST.get("bookingID")
        booking = get_object_or_404(BookingRequest, id=booking_id)

        if booking.company == company:
            booking.delete()
            return JsonResponse({"result": "Success!"})
        return JsonResponse({"result": "Unauthorized Access!"})

    raise Http404("Page Doesn't Exist!")


@login_required
@manager_required
def booking_setup_view(request):
    if request.is_ajax and request.method == "POST":
        booking_id = request.POST.get("bookingID")
        booking = get_object_or_404(BookingRequest, id=booking_id)
        booking.status = "unbooked"
        booking.save()

        email_booking_confirmed(booking)
        return JsonResponse({"result": "Success!"})

    raise Http404("Page Doesn't Exist!")


@method_decorator([login_required], name='dispatch')
class BookmarkedView(LoginRequiredMixin, ListView):
    template_name = "users/my_bookmarks.html"
    context_object_name = "bookmarks"
    paginate_by = 10

    def get_queryset(self):
        return BookmarkedProperty.objects.filter(
            owner=self.request.user)


@login_required
@manager_required
def bookmark_delete_view(request):
    company = get_object_or_404(Company, manager=request.user)

    if request.is_ajax and request.method == "POST":
        bookmark_id = request.POST.get("bookmarkID")
        bookmark = get_object_or_404(BookmarkedProperty, id=bookmark_id)

        if bookmark.property_obj.owner == company:
            bookmark.delete()
            return JsonResponse({"result": "Success!"})
        return JsonResponse({"result": "Unauthorized Access!"})

    raise Http404("Page Doesn't Exist!")


@method_decorator([login_required], name='dispatch')
class MyAccountView(TemplateView):

users/templates/user_components/dashboard__footer.html
{% load static %}

    <div class="dash-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="copyright">
                        <p>© 2020 Darader. All rights reserved.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

users/templates/user_components/dashboard__header.html
{% load static %}

<header class="db-top-header">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-md-9 col-sm-6 col-4">
                <div class="site-navbar-wrap v2 style2">
                    <div class="site-navbar">
                        <nav class="site-navigation">
                            <div class="container">
                                <ul class="site-menu js-clone-nav d-none d-lg-block">
                                    <li>
                                        <a href="{% url 'properties:home' %}">Home</a>                                                
                                    </li>
                                    <li>
                                        <a href="{% url 'properties:rent' %}">For Rent</a>                                                
                                    </li>
                                    <li>
                                        <a href="{% url 'properties:sale' %}">For Sale</a>                                                
                                    </li>
                                    <li>
                                        <a href="{% url 'properties:lease' %}">For Lease</a>                                                
                                    </li>  
                                    <li>
                                        <a href="{% url 'properties:contact' %}">Contact us</a>                                                
                                    </li>     
                                    <!-- <li>
                                        <a href="{% url 'properties:faq' %}">FAQ</a>                                                
                                    </li>                                                                 -->
                                </ul>
                            </div>
                        </nav>
                        <div class="d-lg-none sm-right">
                            <a href="#" class="mobile-bar js-menu-toggle">
                                <span class="lnr lnr-menu"></span>
                            </a>
                        </div>
                        <!--mobile-menu starts -->
                        <div class="site-mobile-menu">
                            <div class="site-mobile-menu-header">
                                <div class="site-mobile-menu-close  js-menu-toggle">
                                    <span class="lnr lnr-cross"></span> </div>
                            </div>
                            <div class="site-mobile-menu-body"></div>
                        </div>
                        <!--mobile-menu ends-->
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-8">
                <div class="header-button">
                    <!-- <div class="header-button-item has-noti js-item-menu">
                        <i class="ion-ios-bell-outline"></i>
                        <div class="notifi-dropdown js-dropdown">
                            <div class="notifi__item">
                                <div class="content">
                                    <p>Your Property <b>Villa On Hartford</b> has been approved!</p>
                                    <span class="date">5 min ago</span>
                                </div>
                            </div>
                            <div class="notifi__item">
                                <div class="content">
                                    <p>You have 3 unread Messages</p>
                                    <span class="date">5 min ago</span>
                                </div>
                            </div>
                            <div class="notify-bottom text-center py-20">
                                <a href="#">View All Notification</a>
                            </div>
                        </div>
                    </div> -->
                    <div class="header-button-item js-sidebar-btn">
                        <img src="https://ui-avatars.com/api/?background=0072b1&color=ffffff&name={{user}}" alt="...">
                        <span>{% if user.full_name %}{{ user.full_name}}{% else %}{{ user|title }}{% endif %} <i class="ion-arrow-down-b"></i></span>
                    </div>
                    <div class="setting-menu js-right-sidebar d-none d-lg-block">
                        <div class="account-dropdown__body">
                            <div class="account-dropdown__item">
                                <a href="{% url 'users:account' %}">
                                    Profile</a>
                            </div>
                            <div class="account-dropdown__item">
                                <a href="{% url 'properties:logout' %}">
                                    Logout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

users/templates/user_components/dashboard__sidebar.html
{% load static %}

<aside class="menu-sidebar js-right-sidebar d-block">
    <div class="logo">
        <a href="{% url 'users:dashboard' %}">
            <img src="{% static 'assets/images/logo-blue.png' %}" alt="SarchHolm" />
        </a>
    </div>
    <div class="menu-sidebar__content js-scrollbar2">
        <nav class="navbar-sidebar2">
            <ul class="list-unstyled navbar__list">
                <li>
                    <a {% if 'my/dashboard' in request.path %}class="active" {% endif %}
                        href="{% url 'users:dashboard' %}">
                        <i class="ion-ios-gear-outline"></i>Dashboard
                    </a>
                </li>
                {% if user.is_admin or user.is_staff %}
                <li>
                    <a {% if 'my/properties/manage' in request.path %}class="active" {% endif %}
                        href="{% url 'users:manage-properties' %}">
                        <i class="ion-social-buffer-outline"></i>Manage Properties
                    </a>
                </li>
                <li>
                    <a {% if 'hotels/my-hotels' in request.path %}class="active" {% endif %}
                        href="{% url 'hotels:my-hotels' %}">
                        <i class="ion-social-buffer-outline"></i>My Hotels
                    </a>
                </li>
                <li>
                    <a {% if 'hotels/add-hotel' in request.path %}class="active" {% endif %}
                        href="{% url 'hotels:add-hotel' %}">
                        <i class="ion-ios-plus-outline"></i>Add Hotel
                    </a>
                </li>
                {% endif %}

                <li>
                    <a {% if 'my/bookings' in request.path %}class="active" {% endif %}
                        href="{% url 'users:bookmarked' %}">
                        <i class="ion-ios-heart-outline"></i>Bookmarks</a>
                </li>
                {% if user.is_account_manager %}
                <li>
                    <a {% if 'my/properties' in request.path %}class="active" {% endif %}
                        href="{% url 'users:my-properties' %}">
                        <i class="ion-social-buffer-outline"></i>My Properties
                    </a>
                </li>
                {% if user.company.exists %}
                <li>
                    <a {% if 'my/company/update' in request.path %}class="active" {% endif %}
                        href="{% url 'users:update-company' %}">
                        <i class="ion-ios-plus-outline"></i>Update Company
                    </a>
                </li>
                <li>
                    <a {% if 'my/add-property' in request.path %}class="active" {% endif %}
                        href="{% url 'users:add-property' %}">
                        <i class="ion-ios-plus-outline"></i>Add Property</a>
                </li>
                {% else %}
                <li>
                    <a {% if 'my/company/add' in request.path %}class="active" {% endif %}
                        href="{% url 'users:add-company' %}">
                        <i class="ion-ios-plus-outline"></i>Setup Company
                    </a>
                </li>
                {% endif %}
                <li>
                    <a {% if 'my/bookings' in request.path %}class="active" {% endif %}
                        href="{% url 'users:my-bookings' %}">
                        <i class="ion-ios-copy-outline"></i>Booking Request</a>
                </li>

                {% endif %}
                <li>
                    <a {% if 'my/account' in request.path %}class="active" {% endif %} href="{% url 'users:account' %}">
                        <i class="ion-ios-person-outline"></i>My profile</a>
                </li>
                <li>
                    <a {% if '/logout' in request.path %}class="active" {% endif %}
                        href="{% url 'properties:logout' %}">
                        <i class="ion-ios-upload-outline"></i>Logout</a>
                </li>
            </ul>
        </nav>
    </div>
</aside>